### ISSUE TITLE
New install cant import Blue skyRun

### ISSUE THREAD

**Issue by ercius** [synchrotrons/Xi-cam.plugins#16]
I just reinstalled xicam on a new windows 10 machine using anaconda and python 3.7. The following package (BlueskyRun) is not automatically installed and I cant find a way to install it. Was this not added to the requirements file?

https://github.com/synchrotrons/Xi-cam.plugins/blob/4551313f5b94046fd4bd241ce1b0a136db62f494/xicam/plugins/guiplugin.py#L6

**Comment by ercius** [comment]
This is user in one function which is just a pass. So, the import and function can be commented out for now to get things running again.

**Comment by ronpandolfi** [comment]
`databroker` is already listed in the requirements, however the version currently picked up by pip will be a beta v0.* version; we are developing against a pre-release version. AFAIK, there's no way to pin against it yet in our `setup.py`, @tacaswell .

To fix this for now, you can explicitly install the pre-release version with `pip install --upgrade --ignore-installed --pre --no-cache-dir databroker`

**Comment by ercius** [comment]
The `--ignore-installed` will upgrade every package and not just databroker (i.e. numpy) My virtual environment for xicam now won't start. Numpy wont load when I try to import it in this environment. It is likely related to a local error I got during the install related to having python running in another command prompt.

Ill reinstall from scratch and see if I can get it running again. I dont suggest running that pip update until we can figure out how to make it ignore all of the other packages.

**Comment by ercius** [comment]
Ok...I reinstalled everything and now it works. I think removing the --ignore-installed will still get the proper version.

**Comment by ronpandolfi** [comment]
@ercius , sorry for the mixup; I wasn't expecting that. Glad you got it working. I've added a pinned requirement to Xi-cam, so this shouldn't come up again.
